definitions:
  tests: &test
    name: Tests
    image: adaptavist/terraform:alpine-0.12.8-dev
    script:
      - (echo ${PIPELINE_GIT_PRIVATE_KEY} | base64 -d >> ~/.ssh/id_rsa) && chmod 0600 ~/.ssh/id_rsa
      - terraform fmt -check -recursive -diff

  release: &release
      name: release
      image: ghcr.io/adaptavist/docker-semantic-release:17.4.2-alpine3.11
      script:
        - semantic-release -r ${BITBUCKET_GIT_HTTP_ORIGIN}

  checkov-image: &checkov-image
    name: bridgecrew/checkov:latest
    entrypoint:
      - '/usr/bin/env'
      - 'PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin'

  scripts:
    - &checkov >
      checkov --quiet --compact -s -d . -o github_failed_only > compliance-issues.md &&
      checkov --quiet --compact -s -d .

pipelines:
  default:
    - step: *test
    - step: { name: 'Checkov analysis', script: [ *checkov ], image: *checkov-image, services: [ docker ] } 
  branches:
    master:
      - step: *test
      - step: *release